Hw12 13 14 15 calendar
ezhk/golang-learning pull request #19
Opened 2020-09-02 18:45 UTC by ezhk

## Домашнее задание №12 «Заготовка сервиса Календарь»

### Критерии оценки
- [ ] Makefile заполнен и пайплайн зеленый - 1 балл
- [ ] Понятность и чистота кода (включая факт, что проект разбит
на пакеты по определенной логике) - до 2 баллов
- [ ] Реализовано конфигурирование сервиса - 1 балл
- [ ] Используется логгер и он настраивается из конфига - 1 балл
- [ ] Запускается простой HTTP-сервер - 1 балл
- [ ] Присутствуют юнит-тесты - 1 балл

Реализовано хранилище:
- [ ] in-memory - 1 балл
- [ ] sql + миграции - 2 балла

#### Зачёт от 7 баллов

2020-09-20 08:22 UTC, Antonboom requested changes
https://otus.ru/teacher-lk/homework/23752/7011/

Здравствуйте!

Хорошая работа, но слишком много замечаний, в основном по структуре приложения и архитектуре.
Предварительно
5 / 10

2020-09-20 08:22 UTC, Antonboom commented on hw12_13_14_15_calendar/LICENSE
> +   Copyright [yyyy] [name of copyright owner]
а чей копирайт-то?

2020-09-20 08:22 UTC, Antonboom commented on hw12_13_14_15_calendar/cmd/calendar.go
> +/*
весь мусор от кобры можно убрать

2020-09-20 08:22 UTC, Antonboom commented on hw12_13_14_15_calendar/database/database.go
> +package database
посмотрите пример заготовки ДЗ в базовой репе - на верхнем уровне не должно быть пакетов кроме cmd/pkg/internal

2020-09-20 08:22 UTC, Antonboom commented on hw12_13_14_15_calendar/server/server_test.go
> +		require.Nil(t, err)
при желании можно `require.NoError`

2020-09-20 08:22 UTC, Antonboom commented on hw12_13_14_15_calendar/go.mod
> +go 1.15
в трависе 1.14 - норм работает?

2020-09-20 08:22 UTC, Antonboom commented on hw12_13_14_15_calendar/cmd/calendar.go
> +		err := HTTPServer.Run()
- не хватает обработки сигналов от ОС
- не хватает shutdown'а сервера

2020-09-20 08:22 UTC, Antonboom commented on hw12_13_14_15_calendar/cmd/calendar.go
> +		HTTPServer := server.NewHTTPServer(log)
не хватает инициализации БД и самого приложения

см. заготовку

2020-09-20 08:22 UTC, Antonboom commented on hw12_13_14_15_calendar/database/database.go
> +	ID        int       `db:"id"`
в данном задании нельзя пользоваться ORM (кроме sqlx), так что вопрос, понадобятся ли тэги

2020-09-20 08:22 UTC, Antonboom commented on hw12_13_14_15_calendar/logger/logger.go
> +		log.Fatalf("can't initialize zap logger: %v", err)
возвращать ошибку наверх, фаталить в мейне

2020-09-20 08:22 UTC, Antonboom commented on hw12_13_14_15_calendar/logger/logger.go
> +		switch v {
можно strings.Lower

2020-09-20 08:22 UTC, Antonboom commented on hw12_13_14_15_calendar/database/memory.go
> +type MemoryDatabase struct {
не хватает RWMutex'а

2020-09-20 08:22 UTC, Antonboom commented on hw12_13_14_15_calendar/database/memory.go
> +		if u.ID == id {
O(n)

2020-09-20 08:22 UTC, Antonboom commented on hw12_13_14_15_calendar/database/memory.go
> +		if u.ID == id {
O(n)

2020-09-20 08:22 UTC, Antonboom commented on hw12_13_14_15_calendar/database/memory.go
> +	Users []User
Не оптимальная структура хранения данных

2020-09-20 08:22 UTC, Antonboom commented on hw12_13_14_15_calendar/database/memory.go
> +	return errors.New("record not found")
ошибки выводить в отдельные переменные

2020-09-20 08:22 UTC, Antonboom commented on hw12_13_14_15_calendar/database/memory_test.go
> +func TestDatabase(t *testing.T) {
не хватает теста на конкурентный доступ

2020-09-20 08:22 UTC, Antonboom commented on hw12_13_14_15_calendar/logger/logger.go
> +	config := prepareConfig()
конфиг должен пробрасываться извне и он скорее всего будет частью глобального конфига приложения

2020-09-26 15:16 UTC, ezhk commented on hw12_13_14_15_calendar/logger/logger.go
> +	config := prepareConfig()
Унес в отдельный модуль работу с конфигом.

2020-09-26 15:17 UTC, ezhk commented on hw12_13_14_15_calendar/database/memory.go
> +	return errors.New("record not found")
Общие поправил, как быть со форматированным описанием:
`fmt.Errorf("failed to load driver: %q", err)`
?

2020-09-26 15:18 UTC, ezhk commented on hw12_13_14_15_calendar/database/memory.go
> +	Users []User
Поправил, но будет гораздо интереснее как потом в in-memory 
сделать быстрый доступ по событиям за последнюю неделю/месяц и пр?
В SQL понятно как это сделать просто :)

2020-09-26 15:19 UTC, ezhk commented on hw12_13_14_15_calendar/database/memory.go
> +		if u.ID == id {
Оптимизировал, но для in-memory будет большая избыточность.
Ведь нам, по сути, надо делать реализацию индексов в каком-то простом виде.

2020-09-26 15:19 UTC, ezhk commented on hw12_13_14_15_calendar/cmd/calendar.go
> +		err := HTTPServer.Run()
Done.

2020-09-26 15:20 UTC, ezhk commented on hw12_13_14_15_calendar/database/database.go
> +	ID        int       `db:"id"`
Теги не понадобятся в рамках задания точно,
в бекграунде потом думал ORM попробовать — поэтому не убирал.

2020-09-26 15:20 UTC, ezhk commented on hw12_13_14_15_calendar/go.mod
> +go 1.15
Тесты проходит. Или я не понял вопрос?

2020-09-26 15:20 UTC, ezhk commented on hw12_13_14_15_calendar/server/server_test.go
> +		require.Nil(t, err)
Спасибо.

2020-09-26 15:21 UTC, ezhk commented on hw12_13_14_15_calendar/database/database.go
> +package database
Переделал структуру.

2020-09-26 15:21 UTC, ezhk commented on hw12_13_14_15_calendar/cmd/calendar.go
> +/*
Почистил.

2020-09-26 15:21 UTC, ezhk commented on hw12_13_14_15_calendar/LICENSE
> +   Copyright [yyyy] [name of copyright owner]
Обновил :)

2020-09-28 08:15 UTC, Antonboom commented on hw12_13_14_15_calendar/go.mod
> +go 1.15
вопрос был в том, что у вас проект для гошки 1.15, а собирается под 1.14

2020-09-28 08:17 UTC, Antonboom commented on hw12_13_14_15_calendar/database/memory.go
> +	return errors.New("record not found")
На выбор:

- игнорим тип ошибки
```golang
fmt.Errorf("failed to load driver: %v", err)
```

- врапим ошибку
```golang
fmt.Errorf("failed to load driver: %w", err)
```

- врапим ошибку в свою ошибку
```golang
fmt.Errorf(ErrLoadDriver, "%v", err)
```

2020-09-28 08:19 UTC, Antonboom approved these changes
10 / 10

2020-09-28 10:14 UTC, merged